version: '3.9'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    restart: always
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
    depends_on:
      - db

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8080:8080
volumes:
    pgdata:
        external: true
