# Generated by Django 3.2.1 on 2021-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(),
        ),
    ]
