# Generated by Django 3.2.1 on 2021-05-05 21:36

from django.db import migrations, models
import helpers.form_validator


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_auto_20210505_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(validators=[helpers.form_validator.validate_year_class]),
        ),
    ]
