# Generated by Django 3.2.1 on 2021-05-06 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0007_auto_20210505_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
