# Generated by Django 3.2.1 on 2021-05-06 12:31

from django.db import migrations, models
import school_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_alter_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=school_app.models.upload_path_handler),
        ),
    ]
